# Generated by Django 5.2.4 on 2025-07-12 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_bloque', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_cluster', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criticidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_criticidad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_estado', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoResolutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_grupo_resol', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_impacto', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interfaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_interfaz', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Severidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_severidad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_aplicacion', models.CharField(max_length=50, unique=True)),
                ('nombre_aplicacion', models.CharField(max_length=255)),
                ('desc_aplicacion', models.TextField(blank=True, null=True)),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.bloque')),
                ('criticidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.criticidad')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.estado')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cierre', models.CharField(max_length=50, unique=True)),
                ('desc_cod_cierre', models.CharField(blank=True, max_length=255, null=True)),
                ('causa_cierre', models.TextField(blank=True, null=True)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_cierre', to='gestion.aplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidencia', models.CharField(max_length=50, unique=True)),
                ('descripcion_incidencia', models.TextField(blank=True)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_resolucion', models.DateTimeField(blank=True, null=True)),
                ('causa', models.TextField(blank=True)),
                ('bitacora', models.TextField(blank=True)),
                ('tec_analisis', models.TextField(blank=True)),
                ('correccion', models.TextField(blank=True)),
                ('solucion_final', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario_asignado', models.CharField(blank=True, max_length=150)),
                ('demandas', models.TextField(blank=True)),
                ('workaround_disponible', models.BooleanField(default=False)),
                ('workaround_detalle', models.TextField(blank=True)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='gestion.aplicacion')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='gestion.bloque')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='gestion.cluster')),
                ('codigo_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='gestion.codigocierre')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='gestion.estado')),
                ('grupo_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to='gestion.gruporesolutor')),
                ('grupo_resolutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_resueltas', to='gestion.gruporesolutor')),
                ('impacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='gestion.impacto')),
                ('interfaz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='gestion.interfaz')),
                ('severidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='gestion.severidad')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
