# Generated by Django 5.2.4 on 2025-08-15 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_bloque', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_cluster', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criticidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_criticidad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del día feriado.', unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Día Feriado',
                'verbose_name_plural': 'Días Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_estado', models.CharField(max_length=100, unique=True)),
                ('uso_estado', models.CharField(blank=True, choices=[('Incidencia', 'Incidencia'), ('Aplicacion', 'Aplicacion')], help_text='Selecciona dónde se utiliza principalmente este estado.', max_length=50, verbose_name='Uso del Estado')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoResolutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_grupo_resol', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'LUNES'), (1, 'MARTES'), (2, 'MIÉRCOLES'), (3, 'JUEVES'), (4, 'VIERNES'), (5, 'SÁBADO'), (6, 'DOMINGO')], unique=True)),
                ('hora_inicio', models.TimeField(blank=True, help_text='Dejar en blanco si es un día no laboral (CERRADO)', null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Horario Laboral',
                'verbose_name_plural': 'Horarios Laborales',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Impacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_impacto', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interfaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_interfaz', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Severidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_severidad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_aplicacion', models.CharField(max_length=50, unique=True)),
                ('nombre_aplicacion', models.CharField(max_length=255)),
                ('desc_aplicacion', models.TextField(blank=True, null=True)),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.bloque')),
                ('criticidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.criticidad')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.estado')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cierre', models.CharField(max_length=50)),
                ('desc_cod_cierre', models.TextField(blank=True, default='')),
                ('causa_cierre', models.TextField(blank=True, default='')),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_cierre', to='gestion.aplicacion')),
            ],
            options={
                'unique_together': {('cod_cierre', 'aplicacion')},
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidencia', models.CharField(max_length=50, unique=True)),
                ('descripcion_incidencia', models.TextField(blank=True)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_resolucion', models.DateTimeField(blank=True, null=True)),
                ('causa', models.TextField(blank=True)),
                ('bitacora', models.TextField(blank=True)),
                ('tec_analisis', models.TextField(blank=True)),
                ('correccion', models.TextField(blank=True)),
                ('solucion_final', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('demandas', models.TextField(blank=True)),
                ('workaround', models.CharField(choices=[('No', 'No'), ('Sí', 'Sí')], default='No', max_length=2)),
                ('cumple_sla', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No'), ('N/A', 'No Aplica')], default='N/A', max_length=20, null=True, verbose_name='Cumple SLA')),
                ('tiempo_sla_calculado', models.DurationField(blank=True, help_text='Tiempo de gestión laboral calculado para el SLA.', null=True, verbose_name='Tiempo de Gestión (SLA)')),
                ('aplicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='gestion.aplicacion')),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='gestion.bloque')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='gestion.cluster')),
                ('codigo_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='gestion.codigocierre')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='gestion.estado')),
                ('grupo_resolutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_resueltas', to='gestion.gruporesolutor')),
                ('impacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='gestion.impacto')),
                ('interfaz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='gestion.interfaz')),
                ('severidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='gestion.severidad')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to='gestion.usuario')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='ReglaSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_sla', models.DurationField(help_text='Tiempo máximo de resolución en formato DD HH:MM:SS')),
                ('criticidad_aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.criticidad')),
                ('severidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.severidad')),
            ],
            options={
                'verbose_name': 'Regla de SLA',
                'verbose_name_plural': 'Reglas de SLA',
                'unique_together': {('severidad', 'criticidad_aplicacion')},
            },
        ),
    ]
