# Generated by Django 5.2.4 on 2025-08-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='demandas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
