# Generated by Django 5.2.4 on 2025-08-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_incidencia_demandas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='cumple_sla',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No'), ('N/A', 'No Aplica')], default='N/A', max_length=50, null=True, verbose_name='Cumple SLA'),
        ),
    ]
