# Generated by Django 5.2.4 on 2025-07-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='workaround_disponible',
            new_name='workaround',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='grupo_asignado',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='workaround_detalle',
        ),
    ]
