# Generated by Django 5.2.4 on 2025-07-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_workaround_disponible_incidencia_workaround_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='workaround',
            field=models.CharField(choices=[('No', 'No'), ('Sí', 'Sí')], default='No', max_length=2),
        ),
    ]
