# Generated by Django 5.2.4 on 2025-07-17 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to='gestion.usuario'),
        ),
    ]
