# Generated by Django 5.2.4 on 2025-07-22 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_incidencia_usuario_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='aplicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='gestion.aplicacion'),
        ),
    ]
