# Generated by Django 5.2.4 on 2025-07-22 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_incidencia_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='bloque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='gestion.bloque'),
        ),
    ]
