# Generated by Django 5.2.4 on 2025-07-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_add_initial_users'),
        ('gestion', '0008_alter_incidencia_bloque'),
    ]

    operations = [
    ]
