# Generated by Django 5.2.4 on 2025-07-28 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_merge_20250728_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del día feriado.', unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Día Feriado',
                'verbose_name_plural': 'Días Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'LUNES'), (1, 'MARTES'), (2, 'MIÉRCOLES'), (3, 'JUEVES'), (4, 'VIERNES'), (5, 'SÁBADO'), (6, 'DOMINGO')], unique=True)),
                ('hora_inicio', models.TimeField(blank=True, help_text='Dejar en blanco si es un día no laboral (CERRADO)', null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Horario Laboral',
                'verbose_name_plural': 'Horarios Laborales',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='ReglaSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_sla', models.DurationField(help_text='Tiempo máximo de resolución en formato DD HH:MM:SS')),
                ('criticidad_aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.criticidad')),
                ('severidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.severidad')),
            ],
            options={
                'verbose_name': 'Regla de SLA',
                'verbose_name_plural': 'Reglas de SLA',
                'unique_together': {('severidad', 'criticidad_aplicacion')},
            },
        ),
    ]
