# Generated by Django 5.2.4 on 2025-07-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_diaferiado_horariolaboral_reglasla'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='cumple_sla',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No'), ('N/A', 'No Aplica')], default='N/A', max_length=20, null=True, verbose_name='Cumple SLA'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tiempo_sla_calculado',
            field=models.DurationField(blank=True, help_text='Tiempo de gestión laboral calculado para el SLA.', null=True, verbose_name='Tiempo de Gestión (SLA)'),
        ),
    ]
