# Generated by Django 5.2.4 on 2025-08-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_incidencia_cumple_sla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigocierre',
            name='cod_cierre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='codigocierre',
            unique_together={('cod_cierre', 'aplicacion')},
        ),
    ]
