# Generated by Django 5.2.4 on 2025-08-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_codigocierre_cod_cierre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigocierre',
            name='causa_cierre',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='codigocierre',
            name='desc_cod_cierre',
            field=models.TextField(blank=True, default=''),
        ),
    ]
