# Generated by Django 5.2.4 on 2025-08-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_codigocierre_causa_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
