# Generated by Django 5.2.4 on 2025-08-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_usuario_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='uso_estado',
            field=models.CharField(blank=True, help_text='Describe dónde se utiliza este estado (ej. Incidencias, Aplicaciones).', max_length=255, verbose_name='Uso del Estado'),
        ),
    ]
