# Generated by Django 5.2.4 on 2025-08-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_estado_uso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='uso_estado',
            field=models.CharField(blank=True, choices=[('Incidencia', 'Incidencia'), ('Aplicacion', 'Aplicacion')], help_text='Selecciona dónde se utiliza principalmente este estado.', max_length=50, verbose_name='Uso del Estado'),
        ),
    ]
